# Generated by Django 6.0.3 on 2026-03-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('aniversario', 'Aniversário'), ('casamento', 'Casamento'), ('noivado', 'Noivado'), ('baptizado', 'Baptizado'), ('cha_de_bebe', 'Chá de bebé'), ('formatura', 'Formatura'), ('conferencia', 'Conferência'), ('reuniao', 'Reunião'), ('evento_corporativo', 'Evento corporativo'), ('outro', 'Outro')], max_length=20),
        ),
    ]
