# Generated by Django 6.0.3 on 2026-03-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventtype_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('aniversario', 'Aniversário'), ('casamento', 'Casamento'), ('noivado', 'Noivado'), ('baptizado', 'Baptizado'), ('cha_de_bebe', 'Chá de bebé'), ('formatura', 'Formatura'), ('conferencia', 'Conferência'), ('reuniao', 'Reunião'), ('evento_corporativo', 'Evento corporativo'), ('outro', 'Outro')], default='aniversario', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='custom_event_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
