# Generated by Django 6.0.3 on 2026-04-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allowed_companions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
