# Generated by Django 6.0.3 on 2026-04-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_allowed_companions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='custom_event_type',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('aniversario', 'Aniversário'), ('casamento', 'Casamento'), ('noivado', 'Noivado'), ('baptizado', 'Baptizado'), ('cha_de_bebe', 'Chá de bebé'), ('formatura', 'Formatura'), ('conferencia', 'Conferência'), ('reuniao', 'Reunião'), ('evento_corporativo', 'Evento corporativo'), ('outro', 'Outro')], default='outro', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
