# Generated by Django 6.0.3 on 2026-03-28 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_event_type_event_custom_event_type_and_more'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='document_id',
        ),
        migrations.AddField(
            model_name='guest',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
