# Generated by Django 6.0.3 on 2026-03-28 16:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_remove_guest_created_at_remove_guest_document_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
