# Generated by Django 6.0.3 on 2026-03-29 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_guest_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('recusado', 'Recusado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='guest',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
