# Generated by Django 6.0.3 on 2026-04-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_guest_qr_code_alter_guest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='allowed_companions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guest',
            name='confirmed_companions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
