# Generated by Django 6.0.3 on 2026-04-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_guest_allowed_companions_guest_confirmed_companions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='allowed_companions',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='confirmed_companions',
        ),
        migrations.AddField(
            model_name='guest',
            name='companion_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
