# Generated by Django 6.0.3 on 2026-03-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_event_type_event_custom_event_type_and_more'),
        ('guests', '0001_initial'),
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('event', 'guest')},
        ),
    ]
